#!/bin/bash
#Assumes you have your config files in an ovpn subdirectory under $HOME
ME=`basename "$0"`
OVPN_PROFILE="$HOME/ovpn/$2.ovpn"

[[ $# -eq 0 || $# -gt 2 ]] || ([[ $# -eq 1 && "$1" != "status" && "$1" != "connected" ]]) || ([[ $# -eq 2 && "$1" != "connect" && "$1" != "disconnect"  && "$1" != "reconnect" && "$1" != "stats" ]]) && { echo "Usage: $ME [(connect|disconnect|reconnect|stats) profile-name | status]"; exit 1; } 

if [[ $1 == "connect" ]]
then
	openvpn3 session-start --config "$OVPN_PROFILE"
fi

if [[ $1 == "disconnect" ]]
then
	openvpn3 session-manage --config "$OVPN_PROFILE" --disconnect
fi

if [[ $1 == "reconnect" ]]
then
        openvpn3 session-manage --config "$OVPN_PROFILE" --restart
fi

if [[ $1 == "status" ]]
then
	openvpn3 sessions-list
fi

if [[ $1 == "stats" ]]
then
        openvpn3 session-stats --config "$OVPN_PROFILE" 
fi

if [[ $1 == "connected" ]]
then
	O_FULL_PROFILE=`openvpn3 sessions-list | grep Config | cut -d' ' -f4`
	O_PROFILE=`echo "${O_FULL_PROFILE}" | cut -d'/' -f5 | cut -d'.' -f1`
	echo $O_PROFILE
fi
